spring:
  datasource:
    username: root
    password: AVaq2218-
    url: jdbc:mysql://localhost:3306/peer_system
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 110MB
      max-request-size: 200MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case=false:


